import requests
from bs4 import BeautifulSoup
import time
import logging


logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

def fetch_and_extract_tokens():
  url = "http://articleapp:80/Articles/Create"
  response = requests.get(url)
  antiforgery_cookie_name = next(
  (name for name in response.cookies.keys() if name.startswith('.AspNetCore.Antiforgery.')), None)
  antiforgery_cookie_value = None if antiforgery_cookie_name is None else response.cookies[antiforgery_cookie_name]

  if response.status_code == 200:
    soup = BeautifulSoup(response.text, 'html.parser')
    token_input = soup.find('input', {'name': '__RequestVerificationToken'})
    if token_input:
      form_token = token_input['value']
      return antiforgery_cookie_value, form_token
  return None, None


def send_post_request():
  #cookie_token, form_token = fetch_and_extract_tokens()
  url = "http://articleapp:80/Articles/Create"

  data = {
    'Author': 'Python',
    'Title': 'Autogenerated',
    'Content': 'LOREM IPSUM',
    'ArticleTagsAsString': 'Tags',
    'Category': 'Politics'
    #'__RequestVerificationToken': form_token
  }

  headers = {
    'Content-Type': 'application/x-www-form-urlencoded'
  }

  #cookies = {
  #  '.AspNetCore.Antiforgery.61MCMJHBRpM': cookie_token
  #}

  response = requests.post(url, data=data, headers=headers)
  logging.info(f"Status Code: {response.status_code}")


while True:
  logging.info("Sending post request")
  time.sleep(10)
  send_post_request()
  time.sleep(60)

