name: ASP.NET Core CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.401'

    - name: Restore dependencies for ArticleApp
      run: dotnet restore ArticleApp/ArticleApp.csproj

    - name: Build ArticleApp
      run: dotnet build ArticleApp/ArticleApp.csproj --no-restore --configuration Release

    - name: Restore dependencies for ArticleAppUnitTests
      run: dotnet restore ArticleAppUnitTests/ArticleAppTests.csproj  # Replace with your test project file name

    - name: Run Unit Tests
      run: dotnet test --filter Category=Unit

    - name: Run Integration Tests
      run: dotnet test --filter Category=Integration